substitutions:
  default_log_level: WARN
  max_log_level: DEBUG
  debug_toggle_switch_active_time_max: "24h"
  uart_logger_baud_rate: "0" # Disable UART, required for TuyaMCU communication
  default_syslog_server_ip: "192.168.0.15"
  default_syslog_server_port: 514
  syslog_log_level: DEBUG
  ntp_timezone: "America/Toronto"
  ntp_server_1: "192.168.0.3"
  ntp_server_2: "192.168.0.250"
  ntp_server_3: "0.pool.ntp.org"
  api_reboot_timeout: 0s # Disable API reboot to prevent dimmer from turning off on reboots
  indicator_brightness_when_offline_percent: 100
  multiclick_min_length: "40ms" # Should be above 30ms
  multiclick_max_length: "350ms"
  longpress_min_length: "1000ms"
  longpress_reboot_timeout: "10s"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: ELEGRP.DTR10/DTR30
    version: "1.6uyat"
  platformio_options:
    build_flags:
      - -DLWIP_DHCP_DOES_ACD_CHECK=0 # fix for https://github.com/libretiny-eu/libretiny/issues/316

bk72xx:
  board: cb2s

packages:
  remote_package_files:
    url: https://github.com/bennydiamond/common_esphome_template/
    files: [arduino.common.yaml]  # optional; if not specified, all files will be included
    ref: master  # optional
    refresh: 1h  # optional      

external_components:
  - source:
      type: git
      url: https://github.com/bennydiamond/esphome-external-uyat
      ref: datapoint_sync_timeout_retries

# Enable Home Assistant API
api:
  id: id_esphome_api
  reboot_timeout: ${api_reboot_timeout}
  # If device disconnected from API for 10 minutes, turn off the indicator LEDs.
  on_client_disconnected:
    if:
      condition:
        for:
          time: 10min
          condition:
            not:
              api.connected:
      then:
        - number.set:
            id: indicator_brightness
            value: ${indicator_brightness_when_offline_percent}

captive_portal:
  id: id_captive_portal

web_server:
  id: id_web_server
  include_internal: True

debug:
  id: id_debug
  update_interval: 30s
  
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

sensor:
  - platform: homeassistant
    name: "HA desired indicator brightness value"
    internal: True
    entity_id: ${indicator_brigtness_value_ha_entity_id}
    on_value: 
      then:
        - number.set:
            id: indicator_brightness
            value: !lambda "return x;"
  - platform: internal_temperature
    name: "CPU Temperature"
    id: id_sensor_internal_temperature
    entity_category: diagnostic
  - platform: debug
    free:
      name: "Heap Free"
    min_free:
      name: "Heap Min Free"
    loop_time:
      name: "Loop Time"

binary_sensor:
  # Requires physical modification to the device to add a second button
  - platform: gpio
    name: "Paddle up"
    id: input_paddle_up_button
    pin:
      number: P6
      inverted: True
      mode:
        input: true
        pullup: false
    filters:
      settle: 50ms
    on_multi_click: 
      - timing: 
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for at least ${multiclick_max_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: up_singleclick
      - timing:
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for ${multiclick_min_length} to ${multiclick_max_length}
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for at least ${multiclick_max_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: up_doubleclick
      - timing: 
          - ON for at least ${longpress_min_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: up_longpress
      - timing: 
          - ON for at least ${longpress_reboot_timeout}
        then:
          - button.press:
              id: id_button_safe_mode

  # Requires physical modification to the device to add a second button
  - platform: gpio
    name: "Paddle down"
    id: input_paddle_down_button
    pin:
      number: P23
      inverted: True
      mode:
        input: true
        pullup: false
    filters:
      settle: 50ms
    on_multi_click: 
      - timing: 
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for at least ${multiclick_max_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: down_singleclick
      - timing:
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for ${multiclick_min_length} to ${multiclick_max_length}
          - ON for ${multiclick_min_length} to ${multiclick_max_length}
          - OFF for at least ${multiclick_max_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: down_doubleclick
      - timing: 
          - ON for at least ${longpress_min_length}
        then:
          - homeassistant.event:
              event: esphome.button_pressed
              data:
                message: down_longpress
      - timing: 
          - ON for at least ${longpress_reboot_timeout}
        then:
          - button.press:
              id: id_button_restart

uyat:
  # DPIDs processed from schema model: 000004ngxw
  id: id_tuya_device
  time_id: id_sntp_time
  ignore_mcu_update_on_datapoints: 
    - 6 # Countdown 1
    - 109 # unknown string
    - 110 # Countdown Action
    - 111 # Countdown Total
    - 113 # unknown string
#  diagnostics:
#    product:
#      name: "Product"
#    num_garbage_bytes:
#      name: "Garbage bytes"
#    unknown_commands:
#      name: "Unknown commands"
#    unknown_extended_commands:
#      name: "Unknown extended commands"
#    unhandled_datapoints:
#      name: "Unhandled datapoints"
#    pairing_mode:
#      name: "Pairing mode"


switch:
  #- platform: uyat
  #  switch_datapoint: 110
  #  name: Countdown Action
  - platform: uyat
    name: "Set Brightness Min"
    id: id_switch_set_brightness_min
    entity_category: config
    datapoint:
      number: 114
      retries:
        enabled: true
        count: 3
        timeout: 600ms

number:
  # Allows for setting brightness value without turning the light ON
  - platform: uyat
    name: "Dimmer Brightness control"
    id: dimmer_brightness_control
    min_value: 1
    max_value: 100
    step: 1
    multiplier: 10 # TuyaMCU scale is 10 to 1000
    datapoint:
      number: 2
      # TuyaMCU scale is 10 to 1000
      # retries already handled by light component, so disable here to avoid double retries
  - platform: uyat
    name: "Longpress Brightness"
    id: id_number_longpress_brightness
    entity_category: config
    min_value: 10
    max_value: 1000
    step: 1
    datapoint:
      number: 108
      retries:
        enabled: true
        count: 3
        timeout: 600ms
  - platform: uyat
    name: "Indicator Brightness"
    id: indicator_brightness
    entity_category: config
    min_value: 0
    max_value: 100
    step: 1
    datapoint: 
      number: 101
      retries:
        enabled: true
        count: 3
        timeout: 600ms
  - platform: uyat
    name: "Brightness Max"
    id: id_number_brightness_max
    entity_category: config
    min_value: 550
    max_value: 1000
    step: 1
    datapoint: 
      number: 5
      # Set Brightness Max does not ack its datapoint update. We're using retries anyway to ensure value is sent to the device.
      retries:
        enabled: true
        count: 2
        timeout: 200ms
  # User must activate "Set Brightness Min" switch before changing the value of this
  - platform: uyat
    name: "Brightness Min"
    id: id_number_brightness_min
    entity_category: config
    min_value: 0
    max_value: 500
    step: 1
    datapoint: 
      number: 3
      retries:
        enabled: true
        count: 3          # retry up to 3 times
        timeout: 600ms    # wait 300ms for MCU acknowledgement
  #- platform: uyat
  #  name: "Countdown 1"
  #  unit_of_measurement: S
  #  datapoint: 
  #    number: 6
  #    min_value: 0
  #    max_value: 86399
  #    step: 1
  #- platform: uyat
  #  name: "Countdown Total"
  #  unit_of_measurement: S
  #  datapoint: 
  #    number: 111
  #    min_value: 0
  #    max_value: 86399
  #    step: 1

select:
  - platform: uyat
    name: "Fade On Speed"
    id: id_select_fade_on_speed
    entity_category: config
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    datapoint: 
      number: 103
      retries:
        enabled: true
        count: 3
        timeout: 600ms
  - platform: uyat
    name: "Fade Off Speed"
    id: id_select_fade_off_speed
    entity_category: config
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    datapoint: 
      number: 104
      retries:
        enabled: true
        count: 3
        timeout: 600ms
  - platform: uyat
    name: "Bulb Type"
    id: id_select_bulb_type
    entity_category: config
    optimistic: true
    options:
      0: "Cfl"
      1: "Incandescent"
      2: "Halogen"
      3: "Led"
    datapoint: 
      number: 4
      retries:
        enabled: true
        count: 3
        timeout: 600ms

light:
  - platform: uyat
    type: dimmer
    name: "Dimmer"
    id: dimmer
    dimmer:
      datapoint: 2
      min_value_datapoint: 2
      min_value: 1
      max_value: 1000
      inverted: false
      retries:
        enabled: true
        count: 3
        timeout: 1000ms
      
    switch:
      datapoint: 1
      inverted: false
      retries:
        enabled: true
        count: 3
        timeout: 300ms
