esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: elegrp.dtr10_dtr30_template
    version: "1.0"

bk72xx:
  board: cb2s

# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}
  # If device disconnected from API for 10 minutes, turn off the indicator LEDs.
  on_client_disconnected:
    if:
      condition:
        for:
          time: 10min
          condition:
            not:
              api.connected:
      then:
        - number.set:
            id: indicator_brightness
            value: ${indicator_brightness_when_offline_percent}

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Power save on LibreTiny is boolean so HIGH or LIGHT have the same effect
  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${hotspot_name}
    password: ${hotspot_password}

captive_portal:

# Enable logging
logger:
  level: ${log_level}
  baud_rate: 0 # Disable log to uart because using Uart for TuyaMCU

web_server:
  port: 80
  version: 3

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

sensor:
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s
    entity_category: diagnostic
    web_server:
      sorting_weight: 202

text_sensor:
  - platform: tuya
    name: "TuyaMCU Version"
    sensor_datapoint: 113
    entity_category: diagnostic
    web_server:
      sorting_weight: 100
  - platform: tuya
    name: "Hardware Version"
    sensor_datapoint: 109
    entity_category: diagnostic
    web_server:
      sorting_weight: 101
  - platform: wifi_info
    ssid:
      name: "WiFi SSID"
      entity_category: diagnostic
      web_server:
        sorting_weight: 201
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
      web_server:
        sorting_weight: 203
    mac_address:
      name: "MAC Address"
      entity_category: diagnostic
      web_server:
        sorting_weight: 204

button:
  - platform: restart
    name: "Device Restart"
    web_server:
      sorting_weight: 300

tuya:
  # DPIDs processed from schema model: 000004ngxw

switch:
  #- platform: tuya
  #  switch_datapoint: 110
  #  name: Countdown Action
  - platform: tuya
    switch_datapoint: 114
    name: "Set Brightness Min"
    entity_category: config
    web_server:
      sorting_weight: 11

number:
  # Allows for setting brightness value without turning the light ON
  - platform: tuya
    number_datapoint: 2
    name: "Dimmer Brightness control"
    min_value: 1
    max_value: 100
    step: 1
    # TuyaMCU scale is 10 to 1000
    multiply: 10 
    web_server:
      sorting_weight: 0
  - platform: tuya
    number_datapoint: 108
    name: "Longpress Brightness"
    min_value: 10
    max_value: 1000
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 1
  - platform: tuya
    number_datapoint: 101
    name: "Indicator Brightness"
    id: indicator_brightness
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 2
  - platform: tuya
    number_datapoint: 5
    name: "Brightness Max"
    min_value: 550
    max_value: 1000
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 10
  # User must activate "Set Brightness Min" switch before changing the value of this
  - platform: tuya
    number_datapoint: 3
    name: "Brightness Min"
    min_value: 0
    max_value: 500
    step: 1
    entity_category: config
    web_server:
      sorting_weight: 12
  #- platform: tuya
  #  number_datapoint: 6
  #  name: "Countdown 1"
  #  unit_of_measurement: S
  #  min_value: 0
  #  max_value: 86399
  #  step: 1
  #- platform: tuya
  #  number_datapoint: 111
  #  name: "Countdown Total"
  #  unit_of_measurement: S
  #  min_value: 0
  #  max_value: 86399
  #  step: 1

select:
  - platform: tuya
    enum_datapoint: 103
    name: "Fade On Speed"
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    entity_category: config
    web_server:
      sorting_weight: 20
  - platform: tuya
    enum_datapoint: 104
    name: "Fade Off Speed"
    optimistic: true
    options:
      0: "Immediate"
      1: "Fast"   # 1s
      2: "Medium" # 5s
      3: "Slow"   # 15s
    entity_category: config
    web_server:
      sorting_weight: 21
  - platform: tuya
    enum_datapoint: 4
    name: "Bulb Type"
    optimistic: true
    options:
      0: "Cfl"
      1: "Incandescent"
      2: "Halogen"
      3: "Led"
    entity_category: config
    web_server:
      sorting_weight: 30

light:
  - platform: tuya
    name: "Dimmer"
    dimmer_datapoint: 2
    min_value_datapoint: 2
    max_value: 1000
    switch_datapoint: 1
    web_server:
      sorting_weight: -1

